/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseInput: typeof import('./src/components/base/BaseInput.vue')['default']
    BaseSearchBar: typeof import('./src/components/base/BaseSearchBar.vue')['default']
    CodeBlock: typeof import('./src/components/createPage/CodeBlock.vue')['default']
    CodeView: typeof import('./src/components/articleDetailPage/CodeView.vue')['default']
    CommonMain: typeof import('./src/components/common/CommonMain.vue')['default']
    CommonNav: typeof import('./src/components/common/CommonNav.vue')['default']
    CreateFooter: typeof import('./src/components/createPage/CreateFooter.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    EntryList: typeof import('./src/components/homePage/EntryList.vue')['default']
    EntryListItem: typeof import('./src/components/homePage/EntryListItem.vue')['default']
    InsertImage: typeof import('./src/components/createPage/menuItem/InsertImage.vue')['default']
    InsertLink: typeof import('./src/components/createPage/menuItem/InsertLink.vue')['default']
    MenuBar: typeof import('./src/components/createPage/MenuBar.vue')['default']
    MenuItem: typeof import('./src/components/createPage/MenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwitchBackgroundColor: typeof import('./src/components/createPage/menuItem/SwitchBackgroundColor.vue')['default']
    SwitchFontColor: typeof import('./src/components/createPage/menuItem/SwitchFontColor.vue')['default']
    Tiptap: typeof import('./src/components/createPage/Tiptap.vue')['default']
    UserInfo: typeof import('./src/components/user/UserInfo.vue')['default']
    UserLogin: typeof import('./src/components/user/UserLogin.vue')['default']
    UserLoginOrRegister: typeof import('./src/components/user/UserLoginOrRegister.vue')['default']
    UserRegister: typeof import('./src/components/user/UserRegister.vue')['default']
  }
}
