name: Build And Deploy To Aliyun ECS

on:                               # 该 CI/CD 触发时的事件
  push:                           # 只要push代码 就触发流程，更多触发事件请参考官方文档
    branches: [ main ]    

jobs:                             # 需要执行的任务，可以有多个任务，所有的 job 都是并行的，但往往会有依赖关系
  build:
    runs-on: ubuntu-latest        # github分配的运行平台，2-core CPU/7 GB of RAM memory/14 GB of SSD disk space
    steps:                        # 某个任务的一系列步骤,如前端需要安装依赖，编译打包代码等等
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 16
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build-only
      
    - name: Deploy to aliyun server        # 为 step 指定一个名称，将会在 github action 的控制台中显示
      uses: easingthemes/ssh-deploy@v2.1.5      #可以访问的仓库，实现的上传服务器步骤被封装在此action
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}  #这个是阿里云的私钥
        ARGS: "-avzr --delete"
        SOURCE: "./html"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}    #阿里云的 ip
        REMOTE_USER: ${{ secrets.REMOTE_USER }}    #阿里云用户
        TARGET: "/nginx"       #被部署的服务器路径 

